### ISSUE TITLE
Pip install not working on macOS Monterey M1

### ISSUE THREAD

**Issue by decause95** [iskandr/fancyimpute#149]
Hi, I'm in a macOS Monterey M1 (2020) and I'm trying to install `fancyimpute` without sucess.

```
Collecting fancyimpute
  Using cached fancyimpute-0.7.0-py3-none-any.whl
Collecting pytest
  Using cached pytest-7.1.3-py3-none-any.whl (298 kB)
Collecting cvxpy
  Using cached cvxpy-1.2.1-cp39-cp39-macosx_10_9_universal2.whl (1.1 MB)
Collecting knnimpute>=0.1.0
  Using cached knnimpute-0.1.0-py3-none-any.whl
Collecting cvxopt
  Using cached cvxopt-1.3.0.tar.gz (4.1 MB)
  Preparing metadata (setup.py) ... done
Collecting nose
  Using cached nose-1.3.7-py3-none-any.whl (154 kB)
Requirement already satisfied: scikit-learn>=0.24.2 in /Users/luisescamez/dcycle/recovo-lca/.venv/lib/python3.9/site-packages (from fancyimpute) (1.1.2)
Requirement already satisfied: six in /Users/luisescamez/dcycle/recovo-lca/.venv/lib/python3.9/site-packages (from knnimpute>=0.1.0->fancyimpute) (1.16.0)
Requirement already satisfied: numpy>=1.10 in /Users/luisescamez/dcycle/recovo-lca/.venv/lib/python3.9/site-packages (from knnimpute>=0.1.0->fancyimpute) (1.23.3)
Requirement already satisfied: threadpoolctl>=2.0.0 in /Users/luisescamez/dcycle/recovo-lca/.venv/lib/python3.9/site-packages (from scikit-learn>=0.24.2->fancyimpute) (3.1.0)
Requirement already satisfied: joblib>=1.0.0 in /Users/luisescamez/dcycle/recovo-lca/.venv/lib/python3.9/site-packages (from scikit-learn>=0.24.2->fancyimpute) (1.2.0)
Requirement already satisfied: scipy>=1.3.2 in /Users/luisescamez/dcycle/recovo-lca/.venv/lib/python3.9/site-packages (from scikit-learn>=0.24.2->fancyimpute) (1.9.1)
Collecting osqp>=0.4.1
  Using cached osqp-0.6.2.post5.tar.gz (226 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Collecting scs>=1.1.6
  Using cached scs-3.2.0-cp39-cp39-macosx_12_0_arm64.whl
Collecting ecos>=2
  Using cached ecos-2.0.10-cp39-cp39-macosx_12_0_arm64.whl
Collecting attrs>=19.2.0
  Using cached attrs-22.1.0-py2.py3-none-any.whl (58 kB)
Requirement already satisfied: packaging in /Users/luisescamez/dcycle/recovo-lca/.venv/lib/python3.9/site-packages (from pytest->fancyimpute) (21.3)
Collecting py>=1.8.2
  Using cached py-1.11.0-py2.py3-none-any.whl (98 kB)
Collecting pluggy<2.0,>=0.12
  Using cached pluggy-1.0.0-py2.py3-none-any.whl (13 kB)
Collecting tomli>=1.0.0
  Using cached tomli-2.0.1-py3-none-any.whl (12 kB)
Collecting iniconfig
  Using cached iniconfig-1.1.1-py2.py3-none-any.whl (5.0 kB)
Collecting qdldl
  Using cached qdldl-0.1.5.post2-cp39-cp39-macosx_12_0_arm64.whl
Requirement already satisfied: pyparsing!=3.0.5,>=2.0.2 in /Users/luisescamez/dcycle/recovo-lca/.venv/lib/python3.9/site-packages (from packaging->pytest->fancyimpute) (3.0.9)
Building wheels for collected packages: cvxopt, osqp
  Building wheel for cvxopt (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> [29 lines of output]
      running bdist_wheel
      running build
      running build_py
      creating build
      creating build/lib.macosx-12-arm64-cpython-39
      creating build/lib.macosx-12-arm64-cpython-39/cvxopt
      copying src/python/misc.py -> build/lib.macosx-12-arm64-cpython-39/cvxopt
      copying src/python/_version.py -> build/lib.macosx-12-arm64-cpython-39/cvxopt
      copying src/python/msk.py -> build/lib.macosx-12-arm64-cpython-39/cvxopt
      copying src/python/__init__.py -> build/lib.macosx-12-arm64-cpython-39/cvxopt
      copying src/python/solvers.py -> build/lib.macosx-12-arm64-cpython-39/cvxopt
      copying src/python/cvxprog.py -> build/lib.macosx-12-arm64-cpython-39/cvxopt
      copying src/python/modeling.py -> build/lib.macosx-12-arm64-cpython-39/cvxopt
      copying src/python/info.py -> build/lib.macosx-12-arm64-cpython-39/cvxopt
      copying src/python/coneprog.py -> build/lib.macosx-12-arm64-cpython-39/cvxopt
      copying src/python/printing.py -> build/lib.macosx-12-arm64-cpython-39/cvxopt
      UPDATING build/lib.macosx-12-arm64-cpython-39/cvxopt/_version.py
      set build/lib.macosx-12-arm64-cpython-39/cvxopt/_version.py to '1.3.0'
      running build_ext
      building 'gsl' extension
      creating build/temp.macosx-12-arm64-cpython-39
      creating build/temp.macosx-12-arm64-cpython-39/src
      creating build/temp.macosx-12-arm64-cpython-39/src/C
      clang -Wno-unused-result -Wsign-compare -Wunreachable-code -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX12.sdk -I/usr/include/gsl -I/Users/luisescamez/dcycle/recovo-lca/.venv/include -I/opt/homebrew/opt/python@3.9/Frameworks/Python.framework/Versions/3.9/include/python3.9 -c src/C/gsl.c -o build/temp.macosx-12-arm64-cpython-39/src/C/gsl.o
      src/C/gsl.c:28:10: fatal error: 'gsl/gsl_rng.h' file not found
      #include <gsl/gsl_rng.h>
               ^~~~~~~~~~~~~~~
      1 error generated.
      error: command '/usr/bin/clang' failed with exit code 1
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for cvxopt
  Running setup.py clean for cvxopt
  Building wheel for osqp (pyproject.toml) ... error
  error: subprocess-exited-with-error
  
  × Building wheel for osqp (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [176 lines of output]
      Disabling LONG
      Remove long integers for numpy compatibility. See:
       - https://github.com/numpy/numpy/issues/5906
       - https://github.com/ContinuumIO/anaconda-issues/issues/3823
      You can reenable long integers by passing: --osqp --long argument.
      
      running bdist_wheel
      running build
      running build_py
      creating build
      creating build/lib.macosx-12-arm64-cpython-39
      creating build/lib.macosx-12-arm64-cpython-39/osqppurepy
      copying src/osqppurepy/interface.py -> build/lib.macosx-12-arm64-cpython-39/osqppurepy
      copying src/osqppurepy/_osqp.py -> build/lib.macosx-12-arm64-cpython-39/osqppurepy
      copying src/osqppurepy/__init__.py -> build/lib.macosx-12-arm64-cpython-39/osqppurepy
      creating build/lib.macosx-12-arm64-cpython-39/osqp
      copying src/osqp/_version.py -> build/lib.macosx-12-arm64-cpython-39/osqp
      copying src/osqp/interface.py -> build/lib.macosx-12-arm64-cpython-39/osqp
      copying src/osqp/__init__.py -> build/lib.macosx-12-arm64-cpython-39/osqp
      copying src/osqp/utils.py -> build/lib.macosx-12-arm64-cpython-39/osqp
      creating build/lib.macosx-12-arm64-cpython-39/osqp/tests
      copying src/osqp/tests/mkl_pardiso_test.py -> build/lib.macosx-12-arm64-cpython-39/osqp/tests
      copying src/osqp/tests/warm_start_test.py -> build/lib.macosx-12-arm64-cpython-39/osqp/tests
      copying src/osqp/tests/polishing_test.py -> build/lib.macosx-12-arm64-cpython-39/osqp/tests
      copying src/osqp/tests/derivative_test.py -> build/lib.macosx-12-arm64-cpython-39/osqp/tests
      copying src/osqp/tests/codegen_matrices_test.py -> build/lib.macosx-12-arm64-cpython-39/osqp/tests
      copying src/osqp/tests/update_matrices_test.py -> build/lib.macosx-12-arm64-cpython-39/osqp/tests
      copying src/osqp/tests/primal_infeasibility_test.py -> build/lib.macosx-12-arm64-cpython-39/osqp/tests
      copying src/osqp/tests/codegen_vectors_test.py -> build/lib.macosx-12-arm64-cpython-39/osqp/tests
      copying src/osqp/tests/utils.py -> build/lib.macosx-12-arm64-cpython-39/osqp/tests
      copying src/osqp/tests/non_convex_test.py -> build/lib.macosx-12-arm64-cpython-39/osqp/tests
      copying src/osqp/tests/unconstrained_test.py -> build/lib.macosx-12-arm64-cpython-39/osqp/tests
      copying src/osqp/tests/dual_infeasibility_test.py -> build/lib.macosx-12-arm64-cpython-39/osqp/tests
      copying src/osqp/tests/basic_test.py -> build/lib.macosx-12-arm64-cpython-39/osqp/tests
      copying src/osqp/tests/feasibility_test.py -> build/lib.macosx-12-arm64-cpython-39/osqp/tests
      copying src/osqp/tests/multithread_test.py -> build/lib.macosx-12-arm64-cpython-39/osqp/tests
      creating build/lib.macosx-12-arm64-cpython-39/osqp/codegen
      copying src/osqp/codegen/__init__.py -> build/lib.macosx-12-arm64-cpython-39/osqp/codegen
      copying src/osqp/codegen/utils.py -> build/lib.macosx-12-arm64-cpython-39/osqp/codegen
      copying src/osqp/codegen/code_generator.py -> build/lib.macosx-12-arm64-cpython-39/osqp/codegen
      creating build/lib.macosx-12-arm64-cpython-39/osqp/tests/solutions
      copying src/osqp/tests/solutions/__init__.py -> build/lib.macosx-12-arm64-cpython-39/osqp/tests/solutions
      creating build/lib.macosx-12-arm64-cpython-39/osqp/codegen/files_to_generate
      copying src/osqp/codegen/files_to_generate/setup.py -> build/lib.macosx-12-arm64-cpython-39/osqp/codegen/files_to_generate
      running egg_info
      writing src/osqp.egg-info/PKG-INFO
      writing dependency_links to src/osqp.egg-info/dependency_links.txt
      writing requirements to src/osqp.egg-info/requires.txt
      writing top-level names to src/osqp.egg-info/top_level.txt
      listing git files failed - pretending there aren't any
      reading manifest file 'src/osqp.egg-info/SOURCES.txt'
      reading manifest template 'MANIFEST.in'
      adding license file 'LICENSE'
      writing manifest file 'src/osqp.egg-info/SOURCES.txt'
      creating build/lib.macosx-12-arm64-cpython-39/extension
      creating build/lib.macosx-12-arm64-cpython-39/extension/include
      copying src/extension/include/osqpinfopy.h -> build/lib.macosx-12-arm64-cpython-39/extension/include
      copying src/extension/include/osqpmodulemethods.h -> build/lib.macosx-12-arm64-cpython-39/extension/include
      copying src/extension/include/osqpobjectpy.h -> build/lib.macosx-12-arm64-cpython-39/extension/include
      copying src/extension/include/osqpresultspy.h -> build/lib.macosx-12-arm64-cpython-39/extension/include
      copying src/extension/include/osqputilspy.h -> build/lib.macosx-12-arm64-cpython-39/extension/include
      copying src/extension/include/osqpworkspacepy.h -> build/lib.macosx-12-arm64-cpython-39/extension/include
      creating build/lib.macosx-12-arm64-cpython-39/extension/src
      copying src/extension/src/.gitignore -> build/lib.macosx-12-arm64-cpython-39/extension/src
      copying src/extension/src/osqpmodule.c -> build/lib.macosx-12-arm64-cpython-39/extension/src
      copying src/osqp/codegen/.gitignore -> build/lib.macosx-12-arm64-cpython-39/osqp/codegen
      copying src/osqp/tests/solutions/test_basic_QP.npz -> build/lib.macosx-12-arm64-cpython-39/osqp/tests/solutions
      copying src/osqp/tests/solutions/test_feasibility_problem.npz -> build/lib.macosx-12-arm64-cpython-39/osqp/tests/solutions
      copying src/osqp/tests/solutions/test_polish_random.npz -> build/lib.macosx-12-arm64-cpython-39/osqp/tests/solutions
      copying src/osqp/tests/solutions/test_polish_simple.npz -> build/lib.macosx-12-arm64-cpython-39/osqp/tests/solutions
      copying src/osqp/tests/solutions/test_polish_unconstrained.npz -> build/lib.macosx-12-arm64-cpython-39/osqp/tests/solutions
      copying src/osqp/tests/solutions/test_solve.npz -> build/lib.macosx-12-arm64-cpython-39/osqp/tests/solutions
      copying src/osqp/tests/solutions/test_unconstrained_problem.npz -> build/lib.macosx-12-arm64-cpython-39/osqp/tests/solutions
      copying src/osqp/tests/solutions/test_update_A.npz -> build/lib.macosx-12-arm64-cpython-39/osqp/tests/solutions
      copying src/osqp/tests/solutions/test_update_A_allind.npz -> build/lib.macosx-12-arm64-cpython-39/osqp/tests/solutions
      copying src/osqp/tests/solutions/test_update_P.npz -> build/lib.macosx-12-arm64-cpython-39/osqp/tests/solutions
      copying src/osqp/tests/solutions/test_update_P_A_allind.npz -> build/lib.macosx-12-arm64-cpython-39/osqp/tests/solutions
      copying src/osqp/tests/solutions/test_update_P_A_indA.npz -> build/lib.macosx-12-arm64-cpython-39/osqp/tests/solutions
      copying src/osqp/tests/solutions/test_update_P_A_indP.npz -> build/lib.macosx-12-arm64-cpython-39/osqp/tests/solutions
      copying src/osqp/tests/solutions/test_update_P_A_indP_indA.npz -> build/lib.macosx-12-arm64-cpython-39/osqp/tests/solutions
      copying src/osqp/tests/solutions/test_update_P_allind.npz -> build/lib.macosx-12-arm64-cpython-39/osqp/tests/solutions
      copying src/osqp/tests/solutions/test_update_bounds.npz -> build/lib.macosx-12-arm64-cpython-39/osqp/tests/solutions
      copying src/osqp/tests/solutions/test_update_l.npz -> build/lib.macosx-12-arm64-cpython-39/osqp/tests/solutions
      copying src/osqp/tests/solutions/test_update_q.npz -> build/lib.macosx-12-arm64-cpython-39/osqp/tests/solutions
      copying src/osqp/tests/solutions/test_update_u.npz -> build/lib.macosx-12-arm64-cpython-39/osqp/tests/solutions
      copying src/osqp/codegen/files_to_generate/CMakeLists.txt -> build/lib.macosx-12-arm64-cpython-39/osqp/codegen/files_to_generate
      copying src/osqp/codegen/files_to_generate/emosqpmodule.c -> build/lib.macosx-12-arm64-cpython-39/osqp/codegen/files_to_generate
      copying src/osqp/codegen/files_to_generate/example.c -> build/lib.macosx-12-arm64-cpython-39/osqp/codegen/files_to_generate
      creating build/lib.macosx-12-arm64-cpython-39/osqp/codegen/sources
      creating build/lib.macosx-12-arm64-cpython-39/osqp/codegen/sources/configure
      copying src/osqp/codegen/sources/configure/osqp_configure.h.in -> build/lib.macosx-12-arm64-cpython-39/osqp/codegen/sources/configure
      copying src/osqp/codegen/sources/configure/qdldl_types.h.in -> build/lib.macosx-12-arm64-cpython-39/osqp/codegen/sources/configure
      creating build/lib.macosx-12-arm64-cpython-39/osqp/codegen/sources/include
      copying src/osqp/codegen/sources/include/CMakeLists.txt -> build/lib.macosx-12-arm64-cpython-39/osqp/codegen/sources/include
      copying src/osqp/codegen/sources/include/auxil.h -> build/lib.macosx-12-arm64-cpython-39/osqp/codegen/sources/include
      copying src/osqp/codegen/sources/include/constants.h -> build/lib.macosx-12-arm64-cpython-39/osqp/codegen/sources/include
      copying src/osqp/codegen/sources/include/error.h -> build/lib.macosx-12-arm64-cpython-39/osqp/codegen/sources/include
      copying src/osqp/codegen/sources/include/glob_opts.h -> build/lib.macosx-12-arm64-cpython-39/osqp/codegen/sources/include
      copying src/osqp/codegen/sources/include/kkt.h -> build/lib.macosx-12-arm64-cpython-39/osqp/codegen/sources/include
      copying src/osqp/codegen/sources/include/lin_alg.h -> build/lib.macosx-12-arm64-cpython-39/osqp/codegen/sources/include
      copying src/osqp/codegen/sources/include/osqp.h -> build/lib.macosx-12-arm64-cpython-39/osqp/codegen/sources/include
      copying src/osqp/codegen/sources/include/proj.h -> build/lib.macosx-12-arm64-cpython-39/osqp/codegen/sources/include
      copying src/osqp/codegen/sources/include/qdldl.h -> build/lib.macosx-12-arm64-cpython-39/osqp/codegen/sources/include
      copying src/osqp/codegen/sources/include/qdldl_interface.h -> build/lib.macosx-12-arm64-cpython-39/osqp/codegen/sources/include
      copying src/osqp/codegen/sources/include/scaling.h -> build/lib.macosx-12-arm64-cpython-39/osqp/codegen/sources/include
      copying src/osqp/codegen/sources/include/types.h -> build/lib.macosx-12-arm64-cpython-39/osqp/codegen/sources/include
      copying src/osqp/codegen/sources/include/util.h -> build/lib.macosx-12-arm64-cpython-39/osqp/codegen/sources/include
      creating build/lib.macosx-12-arm64-cpython-39/osqp/codegen/sources/src
      copying src/osqp/codegen/sources/src/CMakeLists.txt -> build/lib.macosx-12-arm64-cpython-39/osqp/codegen/sources/src
      copying src/osqp/codegen/sources/src/auxil.c -> build/lib.macosx-12-arm64-cpython-39/osqp/codegen/sources/src
      copying src/osqp/codegen/sources/src/error.c -> build/lib.macosx-12-arm64-cpython-39/osqp/codegen/sources/src
      copying src/osqp/codegen/sources/src/kkt.c -> build/lib.macosx-12-arm64-cpython-39/osqp/codegen/sources/src
      copying src/osqp/codegen/sources/src/lin_alg.c -> build/lib.macosx-12-arm64-cpython-39/osqp/codegen/sources/src
      copying src/osqp/codegen/sources/src/osqp.c -> build/lib.macosx-12-arm64-cpython-39/osqp/codegen/sources/src
      copying src/osqp/codegen/sources/src/proj.c -> build/lib.macosx-12-arm64-cpython-39/osqp/codegen/sources/src
      copying src/osqp/codegen/sources/src/qdldl.c -> build/lib.macosx-12-arm64-cpython-39/osqp/codegen/sources/src
      copying src/osqp/codegen/sources/src/qdldl_interface.c -> build/lib.macosx-12-arm64-cpython-39/osqp/codegen/sources/src
      copying src/osqp/codegen/sources/src/scaling.c -> build/lib.macosx-12-arm64-cpython-39/osqp/codegen/sources/src
      copying src/osqp/codegen/sources/src/util.c -> build/lib.macosx-12-arm64-cpython-39/osqp/codegen/sources/src
      running build_ext
      Traceback (most recent call last):
        File "/Users/luisescamez/dcycle/recovo-lca/.venv/bin/cmake", line 5, in <module>
          from cmake import cmake
      ModuleNotFoundError: No module named 'cmake'
      Traceback (most recent call last):
        File "/Users/luisescamez/dcycle/recovo-lca/.venv/lib/python3.9/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 363, in <module>
          main()
        File "/Users/luisescamez/dcycle/recovo-lca/.venv/lib/python3.9/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 345, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "/Users/luisescamez/dcycle/recovo-lca/.venv/lib/python3.9/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 261, in build_wheel
          return _build_backend().build_wheel(wheel_directory, config_settings,
        File "/private/var/folders/9t/622zvlfx2sggc2gtvl9m_60h0000gn/T/pip-build-env-g99b_the/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 412, in build_wheel
          return self._build_with_temp_dir(['bdist_wheel'], '.whl',
        File "/private/var/folders/9t/622zvlfx2sggc2gtvl9m_60h0000gn/T/pip-build-env-g99b_the/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 397, in _build_with_temp_dir
          self.run_setup()
        File "/private/var/folders/9t/622zvlfx2sggc2gtvl9m_60h0000gn/T/pip-build-env-g99b_the/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 335, in run_setup
          exec(code, locals())
        File "<string>", line 256, in <module>
        File "/private/var/folders/9t/622zvlfx2sggc2gtvl9m_60h0000gn/T/pip-build-env-g99b_the/overlay/lib/python3.9/site-packages/setuptools/__init__.py", line 87, in setup
          return distutils.core.setup(**attrs)
        File "/private/var/folders/9t/622zvlfx2sggc2gtvl9m_60h0000gn/T/pip-build-env-g99b_the/overlay/lib/python3.9/site-packages/setuptools/_distutils/core.py", line 185, in setup
          return run_commands(dist)
        File "/private/var/folders/9t/622zvlfx2sggc2gtvl9m_60h0000gn/T/pip-build-env-g99b_the/overlay/lib/python3.9/site-packages/setuptools/_distutils/core.py", line 201, in run_commands
          dist.run_commands()
        File "/private/var/folders/9t/622zvlfx2sggc2gtvl9m_60h0000gn/T/pip-build-env-g99b_the/overlay/lib/python3.9/site-packages/setuptools/_distutils/dist.py", line 968, in run_commands
          self.run_command(cmd)
        File "/private/var/folders/9t/622zvlfx2sggc2gtvl9m_60h0000gn/T/pip-build-env-g99b_the/overlay/lib/python3.9/site-packages/setuptools/dist.py", line 1217, in run_command
          super().run_command(command)
        File "/private/var/folders/9t/622zvlfx2sggc2gtvl9m_60h0000gn/T/pip-build-env-g99b_the/overlay/lib/python3.9/site-packages/setuptools/_distutils/dist.py", line 987, in run_command
          cmd_obj.run()
        File "/private/var/folders/9t/622zvlfx2sggc2gtvl9m_60h0000gn/T/pip-build-env-g99b_the/overlay/lib/python3.9/site-packages/wheel/bdist_wheel.py", line 299, in run
          self.run_command('build')
        File "/private/var/folders/9t/622zvlfx2sggc2gtvl9m_60h0000gn/T/pip-build-env-g99b_the/overlay/lib/python3.9/site-packages/setuptools/_distutils/cmd.py", line 319, in run_command
          self.distribution.run_command(command)
        File "/private/var/folders/9t/622zvlfx2sggc2gtvl9m_60h0000gn/T/pip-build-env-g99b_the/overlay/lib/python3.9/site-packages/setuptools/dist.py", line 1217, in run_command
          super().run_command(command)
        File "/private/var/folders/9t/622zvlfx2sggc2gtvl9m_60h0000gn/T/pip-build-env-g99b_the/overlay/lib/python3.9/site-packages/setuptools/_distutils/dist.py", line 987, in run_command
          cmd_obj.run()
        File "/private/var/folders/9t/622zvlfx2sggc2gtvl9m_60h0000gn/T/pip-build-env-g99b_the/overlay/lib/python3.9/site-packages/setuptools/_distutils/command/build.py", line 132, in run
          self.run_command(cmd_name)
        File "/private/var/folders/9t/622zvlfx2sggc2gtvl9m_60h0000gn/T/pip-build-env-g99b_the/overlay/lib/python3.9/site-packages/setuptools/_distutils/cmd.py", line 319, in run_command
          self.distribution.run_command(command)
        File "/private/var/folders/9t/622zvlfx2sggc2gtvl9m_60h0000gn/T/pip-build-env-g99b_the/overlay/lib/python3.9/site-packages/setuptools/dist.py", line 1217, in run_command
          super().run_command(command)
        File "/private/var/folders/9t/622zvlfx2sggc2gtvl9m_60h0000gn/T/pip-build-env-g99b_the/overlay/lib/python3.9/site-packages/setuptools/_distutils/dist.py", line 987, in run_command
          cmd_obj.run()
        File "/private/var/folders/9t/622zvlfx2sggc2gtvl9m_60h0000gn/T/pip-build-env-g99b_the/overlay/lib/python3.9/site-packages/setuptools/command/build_ext.py", line 84, in run
          _build_ext.run(self)
        File "/private/var/folders/9t/622zvlfx2sggc2gtvl9m_60h0000gn/T/pip-build-env-g99b_the/overlay/lib/python3.9/site-packages/setuptools/_distutils/command/build_ext.py", line 346, in run
          self.build_extensions()
        File "<string>", line 216, in build_extensions
        File "/opt/homebrew/Cellar/python@3.9/3.9.14/Frameworks/Python.framework/Versions/3.9/lib/python3.9/subprocess.py", line 424, in check_output
          return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
        File "/opt/homebrew/Cellar/python@3.9/3.9.14/Frameworks/Python.framework/Versions/3.9/lib/python3.9/subprocess.py", line 528, in run
          raise CalledProcessError(retcode, process.args,
      subprocess.CalledProcessError: Command '['cmake', '--version']' returned non-zero exit status 1.
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for osqp
Failed to build cvxopt osqp
ERROR: Could not build wheels for osqp, which is required to install pyproject.toml-based projects
```

It looks like there is a dependency error from suite-sparse and cmake:

![image](https://user-images.githubusercontent.com/74783341/194098198-a7ee759d-1e5e-4f3a-9e37-c908ad2a8899.png)

My Python version is 3.9.14 and pip version is pip 22.2.2

**Comment by sergeyf** [comment]
Sorry, I am not sure what's going on here. Seems like cvxopt is having trouble? Maybe ask on their github issues page.

**Comment by decause95** [comment]
Hi @sergeyf , thank you very much. I'll post the issue there and link it here. KR.
