### ISSUE TITLE
NameError: global name 'warnings' is not defined

### ISSUE THREAD

**Issue by alitk** [iskandr/fancyimpute#50]
Although I imported warnings package, I keep getting this error while using KNN.
My python version is 2.7.12
`Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/taleb/Python/virtual_environment/local/lib/python2.7/site-packages/fancyimpute/solver.py", line 197, in complete
    imputations = self.multiple_imputations(X)
  File "/home/taleb/Python/virtual_environment/local/lib/python2.7/site-packages/fancyimpute/solver.py", line 189, in multiple_imputations
    return [self.single_imputation(X) for _ in range(self.n_imputations)]
  File "/home/taleb/Python/virtual_environment/local/lib/python2.7/site-packages/fancyimpute/solver.py", line 174, in single_imputation
    X_result = self.solve(X_filled, missing_mask)
  File "/home/taleb/Python/virtual_environment/local/lib/python2.7/site-packages/fancyimpute/knn.py", line 106, in solve
    if warnings:
NameError: global name 'warnings' is not defined
`

**Comment by sergeyf** [comment]
Yeah, we should have fixed that in master, but the pip version is still old. Can you try installing from git and let me know if it's fixed,

@iskandr will you update the pip version please?

**Comment by alitk** [comment]
Git version worked. Thanks for the fast response.

**Comment by sergeyf** [comment]
Great, we'll get it up on pip soon.
