### ISSUE TITLE
Unit tests fail due to Keras import error of np_utils

### ISSUE THREAD

**Issue by iskandr** [iskandr/fancyimpute#61]
```
ERROR: Failure: ImportError (cannot import name np_utils)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/miniconda/envs/test-environment/lib/python2.7/site-packages/nose/loader.py", line 418, in loadTestsFromName
    addr.filename, addr.module)
  File "/home/travis/miniconda/envs/test-environment/lib/python2.7/site-packages/nose/importer.py", line 47, in importFromPath
    return self.importFromDir(dir_path, fqname)
  File "/home/travis/miniconda/envs/test-environment/lib/python2.7/site-packages/nose/importer.py", line 94, in importFromDir
    mod = load_module(part_fqname, fh, filename, desc)
  File "/home/travis/build/iskandr/fancyimpute/test/test_similarity_weighted_averaging.py", line 4, in <module>
    from fancyimpute import SimilarityWeightedAveraging
  File "/home/travis/build/iskandr/fancyimpute/fancyimpute/__init__.py", line 7, in <module>
    from .matrix_factorization import MatrixFactorization
  File "/home/travis/build/iskandr/fancyimpute/fancyimpute/matrix_factorization.py", line 16, in <module>
    from keras import regularizers
  File "/home/travis/miniconda/envs/test-environment/lib/python2.7/site-packages/keras/__init__.py", line 3, in <module>
    from . import utils
  File "/home/travis/miniconda/envs/test-environment/lib/python2.7/site-packages/keras/utils/__init__.py", line 2, in <module>
    from . import np_utils
ImportError: cannot import name np_utils
```

**Comment by iskandr** [comment]
@sergeyf any ideas?

**Comment by sergeyf** [comment]
Well that is weird. You should really be able to do `from keras import regularizers`... Can we try requiring a newer keras?

**Comment by sergeyf** [comment]
You're seeing this on your home machine?
